sudo: required
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_9130ae34a93d_key -iv $encrypted_9130ae34a93d_iv -in simple-k8s-281705-af4d48f505c7.json.enc -out simple-k8s-281705-af4d48f505c7.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file simple-k8s-281705-af4d48f505c7.json
